

let thing1 = 42 + (x * 2) / 1e1;

let thing2 = foo() + std.foo();

let thing3 = begin
                let x = 1;
                try
                    let x = -1_000_000;
                    x * 100
                catch
                    error
                end
                begin
                    let? x = foo.bar()
                    let y = foo().bar()
                    #red
                end
             end

let thing4 =
cond
    x < y -> x;
    x == y -> y * 2
    x > y ->
      begin
        let p = 3
        p + 1
      end
    otherwise -> error
    true -> error
end
